import Logo from '@/assets/img/takomo.svg';
import BannerMobile from '@/assets/img/takomo_banner_mobile.png';
import BackgroundForm from '@/assets/img/takomo_bg.png';

// eslint-disable-next-line import/no-anonymous-default-export
export default {
    logo: Logo,
    backgroundForm: BackgroundForm,
    bannerMobile: BannerMobile,
    primaryColor: '#594DC9',
    offer_id: 'takomo',
    api_check_phone: 'https://ppmob.takomo.vn/v1/4/client/register',
    steps: [
        { title: 'Thông tin\n cá nhân' },
        { title: 'Nơi cư trú và\n làm việc' },
        { title: 'Người thân\n đồng nghiệp' },
        { title: 'Thanh toán\n danh tính' },
    ],
    resident_time: [
        { label: 'Dưới 1 năm', value: '0' },
        { label: '1 năm', value: '1' },
        { label: '2 năm', value: '2' },
        { label: '3 năm', value: '3' },
        { label: '4 năm', value: '4' },
        { label: '5 năm', value: '5' },
        { label: '6 năm', value: '6' },
        { label: '7 năm', value: '7' },
        { label: '8 năm', value: '8' },
        { label: '9 năm', value: '9' },
        { label: '10 năm', value: '10' },
        { label: 'Hơn 10 năm', value: '>10' },
    ],
    marital_status: [
        { label: 'Cưới nhau', value: 'Cưới nhau' },
        { label: 'Đã ly hôn', value: 'Đã ly hôn' },
        { label: 'Độc thân', value: 'Độc thân' },
        { label: 'Góa vợ', value: 'Góa vợ' },
    ],
    job_types: [
        { label: 'Toàn thời gian', value: 'Toàn thời gian' },
        { label: 'Bán thời gian', value: 'Bán thời gian' },
        { label: 'Thất nghiệp', value: 'Thất nghiệp' },
        { label: 'Sinh viên', value: 'Sinh viên' },
        { label: 'Về hưu', value: 'Về hưu' },
        { label: 'Giám đốc', value: 'Giám đốc' },
        { label: 'Nội trợ', value: 'Nội trợ' },
    ],
    job_fields: [
        { label: 'Cảnh sát', value: 'Cảnh sát' },
        { label: 'Quân đội', value: 'Quân đội' },
        { label: 'Tín dụng /Bảo hiểm', value: 'Tín dụng /Bảo hiểm' },
        { label: 'Tài chính / Bất động sản', value: 'Tài chính / Bất động sản' },
        { label: 'Xây dựng', value: 'Xây dựng' },
        { label: 'Công nghệ thông tin', value: 'Công nghệ thông tin' },
        { label: 'Giáo dục', value: 'Giáo dục' },
        { label: 'Chăm sóc sức khoẻ', value: 'Chăm sóc sức khoẻ' },
        { label: 'Dịch vụ khách sạn', value: 'Dịch vụ khách sạn' },
        { label: 'Chế tạo', value: 'Chế tạo' },
        { label: 'Sinh viên', value: 'Sinh viên' },
        { label: 'Bán hàng và marketing', value: 'Bán hàng và marketing' },
        { label: 'Dịch vụ ăn uống', value: 'Dịch vụ ăn uống' },
        { label: 'Dịch vụ vận tải', value: 'Dịch vụ vận tải' },
        { label: 'Bán lẻ', value: 'Bán lẻ' },
        { label: 'Khác', value: 'Khác' },
    ],
    working_time: [
        { label: 'Dưới 1 năm', value: '0' },
        { label: '1 năm', value: '1' },
        { label: '2 năm', value: '2' },
        { label: '3 năm', value: '3' },
        { label: '4 năm', value: '4' },
        { label: '5 năm', value: '5' },
        { label: '6 năm', value: '6' },
        { label: '7 năm', value: '7' },
        { label: '8 năm', value: '8' },
        { label: '9 năm', value: '9' },
        { label: '10 năm', value: '10' },
        { label: 'Hơn 10 năm', value: '>10' },
    ],
    income_range: [
        { label: 'Không có thu nhập', value: 'Không có thu nhập' },
        { label: '1,5 - 3 triệu đồng', value: '1,5 - 3 triệu đồng' },
        { label: '3 - 5 triệu đồng', value: '3 - 5 triệu đồng' },
        { label: '5 - 7 triệu đồng', value: '5 - 7 triệu đồng' },
        { label: '7 - 9 triệu đồng', value: '7 - 9 triệu đồng' },
        { label: '9 - 11 triệu đồng', value: '9 - 11 triệu đồng' },
        { label: '11 - 15 triệu đồng', value: '11 - 15 triệu đồng' },
        { label: '15 - 20 triệu đồng', value: '15 - 20 triệu đồng' },
        { label: 'Trên 20 triệu đồng', value: 'Trên 20 triệu đồng' },
    ],
    personal_relations: [
        { label: 'Vợ / Chồng', value: 'Vợ / Chồng' },
        { label: 'Mẹ ', value: 'Mẹ ' },
        { label: 'Bố', value: 'Bố' },
        { label: 'Anh trai', value: 'Anh trai' },
        { label: 'Khác', value: 'Khác' },
    ],
    purposes: [
        { label: 'Kinh doanh', value: 'Kinh doanh' },
        { label: 'Sửa xe máy', value: 'Sửa xe máy' },
        { label: 'Du lịch', value: 'Du lịch' },
        { label: 'Cần gấp', value: 'Cần gấp' },
        { label: 'Sự kiện quan trọng', value: 'Sự kiện quan trọng' },
        { label: 'Chăm sóc sức khỏe', value: 'Chăm sóc sức khỏe' },
        { label: 'Khác', value: 'Khác' },
    ],
};
