---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: prod-creditvn-web-v1
    namespace: prod
spec:
    selector:
        matchLabels:
            app: prod-creditvn-web-v1
    replicas: 2
    template:
        metadata:
            labels:
                app: prod-creditvn-web-v1
        spec:
            containers:
                - name: prod-creditvn-web-v1
                  image: gcr.io/rio-system-migration/creditvn-web-v1:latest
                  resources:
                      requests:
                          cpu: 100m
                          memory: 256Mi
                  volumeMounts:
                      - name: prod-creditvn-web-v1
                        mountPath: /var/www/html/.env
                        subPath: .env
            volumes:
                - name: prod-creditvn-web-v1
                  configMap:
                      name: prod-creditvn-web-v1

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: prod-creditvn-web-v1
    namespace: prod
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: prod-creditvn-web-v1
    minReplicas: 1
    maxReplicas: 1
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 80
        - type: Resource
          resource:
              name: memory
              target:
                  type: Utilization
                  averageUtilization: 90

---
apiVersion: v1
kind: Service
metadata:
    name: prod-creditvn-web-v1
    namespace: prod
spec:
    selector:
        app: prod-creditvn-web-v1
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
